### ISSUE TITLE
Error with circular deps: level is not defined

### ISSUE THREAD

**Issue by stefanmaric** [seangenabe/browserify-breakdown#1]
```shell
browserify-breakdown < _dist/js/index.min.js 
project/node_modules/browserify-breakdown/index.js:44
          level: level,
                 ^

ReferenceError: level is not defined
    at walk (project/node_modules/browserify-breakdown/index.js:44:18)
    at project/node_modules/browserify-breakdown/index.js:63:14
    at Array.map (native)
    at walk (project/node_modules/browserify-breakdown/index.js:62:28)
    at project/node_modules/browserify-breakdown/index.js:63:14
    at Array.map (native)
    at walk (project/node_modules/browserify-breakdown/index.js:62:28)
    at project/node_modules/browserify-breakdown/index.js:63:14
    at Array.map (native)
    at walk (project/node_modules/browserify-breakdown/index.js:62:28)
```

Using:

`node@6.9.5`
`npm@2.15.11`
`browserify-breakdown@1.0.0`

**Comment by seangenabe** [comment]
Must be a leftover from when I'm thinking the recursive function should remember its depth. I removed the reference to `level`, try it now.

I really should also set up test coverage to catch these... (#2)

**Comment by stefanmaric** [comment]
I grabbed `browserify-breakdown@1.0.1` but a diff error appeared:

```
$ browserify-breakdown < _dist/js/index.min.js
/home/sam/n/lib/node_modules/browserify-breakdown/index.js:103
      sum(node.deps.map(function(dep) { return totalSize(dep, visited) }))
                   ^

TypeError: Cannot read property 'map' of undefined
    at totalSize (/home/sam/n/lib/node_modules/browserify-breakdown/index.js:103:20)
    at /home/sam/n/lib/node_modules/browserify-breakdown/index.js:103:48
    at Array.map (native)
    at totalSize (/home/sam/n/lib/node_modules/browserify-breakdown/index.js:103:21)
    at /home/sam/n/lib/node_modules/browserify-breakdown/index.js:103:48
    at Array.map (native)
    at totalSize (/home/sam/n/lib/node_modules/browserify-breakdown/index.js:103:21)
    at /home/sam/n/lib/node_modules/browserify-breakdown/index.js:103:48
    at Array.map (native)
    at totalSize (/home/sam/n/lib/node_modules/browserify-breakdown/index.js:103:21)
```

**Comment by seangenabe** [comment]
Fixed on https://github.com/seangenabe/browserify-breakdown/commit/b73dce8bd48284d10f1d362df754826d54751c5b .
