### ISSUE TITLE
info[moduleId] is undefined

### ISSUE THREAD

**Issue by keturn** [seangenabe/browserify-breakdown#6]
```
$ npx browserify-breakdown < build/assets/discovery-0.1.0.js
npx: installed 40 in 8.712s
/npm5-cache/_npx/8/lib/node_modules/browserify-breakdown/index.js:52
      size: Buffer.byteLength(info[moduleId].source)
                                            ^

TypeError: Cannot read property 'source' of undefined
    at walk (/npm5-cache/_npx/8/lib/node_modules/browserify-breakdown/index.js:52:45)
    at /npm5-cache/_npx/8/lib/node_modules/browserify-breakdown/index.js:59:14
    at Array.map (native)
    at walk (/npm5-cache/_npx/8/lib/node_modules/browserify-breakdown/index.js:58:28)
    at /npm5-cache/_npx/8/lib/node_modules/browserify-breakdown/index.js:59:14
    at Array.map (native)
    at walk (/npm5-cache/_npx/8/lib/node_modules/browserify-breakdown/index.js:58:28)
    at /npm5-cache/_npx/8/lib/node_modules/browserify-breakdown/index.js:59:14
    at Array.map (native)
    at walk (/npm5-cache/_npx/8/lib/node_modules/browserify-breakdown/index.js:58:28)
```

it does work on the `vendor.js` from the same project, though, which is built using a similar browserify configuration.

**Comment by seangenabe** [comment]
Looks like a loose module ID was referred to that wasn't in the bundle.

Unfortunately I won't be able to go on much further than this without more information.
