### ISSUE TITLE
Example of programmatic use?

### ISSUE THREAD

**Issue by mdvorscak** [seangenabe/browserify-breakdown#7]
Unfortunately for me, on a Windows environment running:
```ps
Get-Content .\_Inc\0.common-factor.js | browserify-breakdown
```

Always throws an error:
> SyntaxError: Error parsing regular expression: Invalid regular expression: /^\-???[\d,]+.?\d*$/: Nothing to repeat (17153:11)
    at Parser.pp$4.raise (C:\Users\mike.dvorscak\AppData\Roaming\npm\node_modules\browserify-breakdown\node_modules\acorn\dist\acorn.js:2488:13)
    at tryCreateRegexp (C:\Users\mike.dvorscak\AppData\Roaming\npm\node_modules\browserify-breakdown\node_modules\acorn\dist\acorn.js:3029:44)
    at Parser.pp$7.readRegexp (C:\Users\mike.dvorscak\AppData\Roaming\npm\node_modules\browserify-breakdown\node_modules\acorn\dist\acorn.js:3090:5)
    at Parser.pp$7.readToken_slash (C:\Users\mike.dvorscak\AppData\Roaming\npm\node_modules\browserify-breakdown\node_modules\acorn\dist\acorn.js:2862:50)
    at Parser.pp$7.getTokenFromCode (C:\Users\mike.dvorscak\AppData\Roaming\npm\node_modules\browserify-breakdown\node_modules\acorn\dist\acorn.js:2988:17)
    at Parser.pp$7.readToken (C:\Users\mike.dvorscak\AppData\Roaming\npm\node_modules\browserify-breakdown\node_modules\acorn\dist\acorn.js:2733:15)
    at Parser.pp$7.nextToken (C:\Users\mike.dvorscak\AppData\Roaming\npm\node_modules\browserify-breakdown\node_modules\acorn\dist\acorn.js:2724:13)
    at Parser.pp$7.next (C:\Users\mike.dvorscak\AppData\Roaming\npm\node_modules\browserify-breakdown\node_modules\acorn\dist\acorn.js:2684:8)
    at Parser.pp.eat (C:\Users\mike.dvorscak\AppData\Roaming\npm\node_modules\browserify-breakdown\node_modules\acorn\dist\acorn.js:555:10)
    at Parser.pp$3.parsePropertyValue (C:\Users\mike.dvorscak\AppData\Roaming\npm\node_modules\browserify-breakdown\node_modules\acorn\dist\acorn.js:2208:12)

I suspect that this is not a problem with acorn, but rather the encoding of the file when windows pipes it's contents to this script.

I might be able to avoid this whole thing by adding a gulp task to do this for me. I looked in the tests and it seems this library works with strings. Will it also work for streams? Maybe you could add some programmatic examples in the README (using gulp, using scripts).

**Comment by seangenabe** [comment]
I checked on regex101 and `/^-???[\d,]+.?\d*$/` _is_ invalid regex, can you check that? I'll update deps if I have to.

I _did_ specify that the API expects `browser-pack` output as the input, which is the same as browserify output. If you want, you can stream into a string and pass that. I'm using [browser-unpack](https://www.npmjs.com/package/get-stream) to parse the string, would you like me to mention that?
